# Generated by Django 5.2.4 on 2025-07-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_video_remove_movies_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age_limit',
        ),
    ]
